### ISSUE TITLE
代码爆显存

### ISSUE THREAD

**Issue by workaholicwjj** [xj-zhu98/KRDN#1]
RuntimeError: CUDA out of memory. Tried to allocate 170.00 MiB (GPU 0; 23.70 GiB total capacity; 21.01 GiB already allocated; 136.56 MiB free; 21.41 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF感觉是够的运行就会报这个错误

**Comment by xj-zhu98** [comment]
I use the A40 for training. If you currently have limited gpu resources, you can lower '--context_hops' and '--max_iter' parameters.
